### ISSUE TITLE
tests/desktop/test_feedback.py should be updated

### ISSUE THREAD

**Issue by willkg** [mozilla/input-tests#146]
In the file:

https://github.com/mozilla/input-tests/blob/master/tests/desktop/test_feedback.py

The following tests should be reimplemented with the new Input:

* test_submitting_feedback_with_unicode_characters
* test_navigating_away_from_initial_submit_feedback_page

I can't tell exactly what "test_navigating_away_from_initial_submit_feedback_page" is intended to test, so it's possible that may not be worth reimplementing.

I think the rest of the tests can be nixed. We don't prevent multiple submissions in a 5 minute window (but probably should) and we don't have a character counter (but probably should).

**Comment by davehunt** [comment]
We're not currently maintaining this repository.
