### ISSUE TITLE
tests/desktop/test_locale_filter.py should be updated

### ISSUE THREAD

**Issue by willkg** [mozilla/input-tests#147]
In the file:

tests/desktop/test_locale_filter.py

the following tests should be reimplemented with the new Input:

* test_feedback_can_be_filtered_by_locale
* test_feedback_can_be_filtered_by_locale_from_expanded_list

Further, "FeedbackPage" should be renamed to "DashboardPage".

The rest of the tests can be nixed.

**Comment by davehunt** [comment]
We're not currently maintaining this repository.
