### ISSUE TITLE
tests/desktop/test_product_filter.py should be updated

### ISSUE THREAD

**Issue by willkg** [mozilla/input-tests#150]
In the file:

tests/desktop/test_product_filter.py

the following tests should be updated:

* test_feedback_can_be_filtered_by_firefox_versions
* test_feedback_can_be_displayed_for_all_firefox_versions

Previously, Input only covered Firefox and Firefox for Android (called "mobile"). Now we support Firefox OS, too. I think if the tests work for Firefox, they should also work for other products, so we don't need to test all products.

**Comment by davehunt** [comment]
We're not currently maintaining this repository.
