### ISSUE TITLE
write test for the firefox os form

### ISSUE THREAD

**Issue by willkg** [mozilla/input-tests#169]
Input currently has two feedback forms: the generic form which covers all products except Firefox OS and the Firefox OS form.

PR #165 covers rewriting the existing feedback form tests to cover the generic feedback form.

This issue covers writing a new test set for the Firefox OS form.

You can get to the Firefox OS form here: https://input.allizom.org/en-US/feedback/fxos

You should use a Firefox OS user agent. This one would be fine:

```
Mozilla/5.0 (Mobile; rv:18.0) Gecko/18.0 Firefox/18.0
```

While the Firefox OS feedback form is a bit different structurally, we can probably start with the generic feedback form and go from there.

**Comment by davehunt** [comment]
We're not currently maintaining this repository.
